# python library

## numpy 
NumPy stands for Numerical Python.

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Thus, numPy is an open source library for the Python programming language, adding support for large, multidimensional arrays, and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
#Install it using this command:
!pip install numpy

# Q- Why is Numpy faster than List?
Due to vectorization.

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
a=[1,2,3]
print (array+10)

TypeError: can only concatenate list (not "int") to list

In [10]:
print(arr+10)

[11 12 13 14 15]


In [3]:
type(arr)

numpy.ndarray

In [11]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## 0-D Array

In [12]:
arr0 = np.array(45)
print(arr0)

45


## 1-D Array

In [13]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


## 2-D Array

In [14]:
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


## 3-D Array

In [15]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
# check the dimension of array
arr2.ndim

2

In [17]:
# create a higher dimmensional array
arr = np.array([1, 2, 3, 4], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


# NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

# Accessing Element

In [18]:
# 1-D array
print(arr1[0])

# 2-D array
print(arr2[1,1])

# 3-D array
print(arr3[1,1,0])

# negative indexing
print(arr3[0,0,-1])

1
2
4
3


# Shape of array

In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr_shape = arr.shape
print(arr_shape)
print(arr_shape[1])

#The example above returns (2, 4), which means that the array has 2 dimensions, 
#where the first dimension has 2 elements and the second has 4.

(2, 4)
4


# Data types

In [22]:
arr = np.array(['apple', 'banana', 'cherry','1'])

print(arr.dtype)

<U6


In [24]:
arr = np.array([1, 2, 3, 4], dtype='int8') # int8, int16, int32

print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [25]:
# convert array to new data type

arr = np.array([1.3, 2.5, 3.6])
print(arr)
print(arr.dtype)

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1.3 2.5 3.6]
float64
[1 2 3]
int32


# Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Reshaping array

In [28]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
# 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [30]:
# 1D to 3D but shape of last dimmension is unknown
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Flattening- from N-D to 1D

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Joining Arrays

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Stacking

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [35]:
# Horizontal Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [36]:
# Vertical Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## numpy_list vs array 

In [37]:
l= [1,2,3,4,5]
a= np.array([1,2,3,4])
l.append(3)
print(l)

[1, 2, 3, 4, 5, 3]


In [38]:
#to insert elements in a new list for doubling elements
l1=[]
for i in l:
    l1.append(i+i)
    
print(l1)

[2, 4, 6, 8, 10, 6]


In [39]:
# to double elements
print(a+a)

[2 4 6 8]


In [31]:
# squaring of elements
#list
l2=[]
for i in l:
    l2.append(i*i)
    
print(l2)

[1, 4, 9, 16, 25, 9]


In [32]:
#array
print(a*a)

[ 1  4  9 16]


In [33]:
# square root of a cube
print(np.sqrt(a*a*a))

#log of a 
print(np.log(a))

[1.         2.82842712 5.19615242 8.        ]
[0.         0.69314718 1.09861229 1.38629436]
